name: Deploy to EC2 with Nginx

# Trigger deployment on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 and Reload Nginx
    runs-on: ubuntu-latest

    steps:
      # Checkout the latest code from the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Deploy files to EC2
      - name: Deploy Files to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ TARGET_DIR }}

      # Run remote commands to reload Nginx
      - name: Reload Nginx on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo nginx -t  # Test Nginx configuration
            sudo systemctl reload nginx  # Reload Nginx to apply changes
